 version: '3'

 services:
   frontend:
     container_name: dr_example_frontend
     hostname: dr_example_frontend
     build: "frontend/"
     command: sh /code/frontend/entrypoint.sh
     working_dir: /code/frontend
     env_file: .env
     ports:
       - 8101:3000
     volumes:
       - ./frontend:/code/frontend
       - '/code/frontend/node_modules'
   db:
     container_name: dr_example_db
     hostname: dr_example_db
     build: "deploy/docker/postgres/"
     env_file: .env
     volumes:
       - pgdata:/var/lib/postgresql/data/ # Preserves db between runs.
     ports:
       - 5432
   backend:
     container_name: dr_example_backend
     hostname: dr_example_backend
     build: .
     command: sh /code/backend/entrypoint.sh
     entrypoint: sh /code/deploy/docker/postgres/wait-for-postgres.sh
     volumes:
       - .:/code
     env_file: .env
     ports:
       - 8000:8000
     links:
       - db
       - frontend
     depends_on:
       - db
       - frontend
 volumes:
     backend:
     frontend:
     pgdata:

